# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "en"
title                    : "FVCproductions"
title_separator          : "-"
name                     : "Frances Coronel"
description              : "I like to dabble with things that ought to be dabbled with."
url                      : "https://fvcproductions.github.io"
baseurl                  : # "/blog"
repository               : "fvcproductions/fvcproductions.github.io"
teaser                   : /assets/images/teaser.png
breadcrumbs              : true
words_per_minute         : 200
comments:
  provider               : "disqus"
  disqus:
    shortname            : "fvcproductions"
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "master"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "docs/_data/comments/{options.slug}" # "/_data/comments/{options.slug}" (default)
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
atom_feed:
  path                   : # blank (default) uses feed.xml

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : "fvcproductions"
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : /assets/images/teaser.png
social:
  type                   : "Organization"
  name                   : "FVCproductions"
  links:
    - "https://twitter.com/fvcproductions"
    - "https://www.linkedin.com/in/fvcproductions"
    - "https://behance.net/fvcproductions"
    - "https://youtube.com/+fvcproductions2013"
    - "https://github.com/fvcproductions"
    - "https://speakerdeck.com/fvcproductions"

# Analytics
analytics:
  provider               : "google"
  google:
    tracking_id          : UA-63190978-3


# Site Author
author:
  name             : "Frances Coronel"
  avatar           : "assets/images/logo-black.svg"
  bio              : "I like to dabble with things that ought to be dabbled with."
  location         : "New York City"
  email            : "fvcproductions at gmail.com"
  uri              : "http://fvcproductions.com"
  behance.net      : "fvcproductions"
  bitbucket        :
  codepen          : "fvcproductions"
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "fvcproductions"
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         : "fvcproductions"
  pinterest        :
  soundcloud       : "fvcproductions"
  stackoverflow    : "3000467/fvcproductions"
  steam            : "fvcproductions"
  tumblr           : "fvcproductions2013"
  twitter          : "fvcproductions"
  vine             :
  weibo            :
  xing             :
  youtube          : "https://youtube.com/c/FVCproductions2013"


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/New_York


# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true
  # _services
  - scope:
      path: ""
      type: services
    values:
      layout: single
      author_profile: false
      share: true
  # _testimonials
  - scope:
      path: ""
      type: testimonials
    values:
      layout: single
      author_profile: false
      share: true

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
  services:
    output: true
    permalink: /:collection/:path/
  testimonials:
    output: true
    permalink: /:collection/:path/

