# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "en"
title                    : "FVCproductions"
title_separator          : "-"
name                     : "Frances Coronel"
description              : "I like to dabble with things that ought to be dabbled with."
url                      : "https://fvcproductions.github.io"
baseurl                  : # "/blog"
repository               : "fvcproductions/fvcproductions.github.io"
teaser                   : /assets/images/teaser.png
words_per_minute         : 200
comments:
  provider               : "disqus"
  disqus:
    shortname            : "fvcproductions"
atom_feed:
  path                   : # blank (default) uses feed.xml

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : "fvcproductions"
og_image                 : /assets/images/teaser.png
social:
  type                   : "Organization"
  name                   : "FVCproductions"
  links:
    - "https://twitter.com/fvcproductions"
    - "https://www.linkedin.com/in/fvcproductions"
    - "https://behance.net/fvcproductions"
    - "https://youtube.com/+fvcproductions2013"
    - "https://github.com/fvcproductions"
    - "https://speakerdeck.com/fvcproductions"

# Analytics
analytics:
  provider               : "google"
  google:
    tracking_id          : UA-63190978-3
# google_analytics:
#   super_proxy_url        : ""

# Site Author
author:
  name             : "Frances Coronel"
  avatar           : "assets/images/logo-black.svg"
  bio              : "I like to dabble with things that ought to be dabbled with."
  location         : "New York City"
  email            : "fvcproductions at gmail.com"
  uri              : "http://fvcproductions.com"
  behance          : "fvcproductions"
  codepen          : "fvcproductions"
  dribbble         : "fvcproductions"
  github           : "fvcproductions"
  google_plus      : "fvcproductions2013"
  instagram        : "fvcproductions"
  linkedin         : "fvcproductions"
  soundcloud       : "fvcproductions"
  stackoverflow    : "3000467/fvcproductions"
  steam            : "fvcproductions"
  tumblr           : "fvcproductions2013"
  twitter          : "fvcproductions"
  youtube          : "FVCproductions2013"


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /blog/:year/:month/:day/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/New_York


# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - algoliasearch-jekyll

# Algolia
algolia:
  application_id: 'LE508NV48J'
  index_name: 'jekyll'
  read_only_api_key: 'd62499d6f6ac2e7850db91168db94083'
  excluded_files:
    - 404.html
    - index.html

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
  # _adventures
  - scope:
      path: ""
      type: adventures
    values:
      layout: single
      read_time: false
      author_profile: false
      share: true
      comments: true
  # _testimonials
  - scope:
      path: ""
      type: testimonials
    values:
      layout: single
      author_profile: false
      share: true
      comments: true
  # _services
  - scope:
      path: ""
      type: services
    values:
      layout: single
      author_profile: false
      share: true
      comment: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true

# Collections
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
  services:
    output: true
    permalink: /:collection/:path/
  testimonials:
    output: true
    permalink: /:collection/:title/
  adventures:
    output: true
    permalink: /:collection/:path/