# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Where things are
source     : ./
destination: ./site

# Site Settings
locale                   : "en"
title                    : "FVCproductions"
title_separator          : "-"
name                     : "Frances Coronel"
description              : "I like to dabble with things that ought to be dabbled with."
url                      : "https://fvcproductions.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "fvcproductions/fvcproductions.github.io"
teaser                   : "/assets/images/teaser.png"
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : "disqus" # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname            : "fvcproductions" # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "master"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "docs/_data/comments/{options.slug}" # "/_data/comments/{options.slug}" (default)
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
atom_feed:
  path                   : # blank (default) uses feed.xml

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Metadata error
github: [metadata]

# Social Sharing
twitter:
  username               : "fvcproductions"
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : "assets/images/teaser.png" # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : "Organization" # Person or Organization (defaults to Person)
  name                   : "FVCproductions" # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - "https://twitter.com/fvcproductions"
    - "https://www.linkedin.com/in/fvcproductions"
    - "https://behance.net/fvcproductions"
    - "https://youtube.com/+fvcproductions2013"
    - "https://github.com/fvcproductions"
    - "https://speakerdeck.com/fvcproductions"

# Analytics
analytics:
  provider               : "google" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : UA-63190978-3


# Site Author
author:
  name             : "Frances Coronel"
  avatar           : "assets/images/logo-black.svg" # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "I like to dabble with things that ought to be dabbled with."
  location         : "San Francisco, CA"
  email            : "fvcproductions at gmail dot com"
  uri              : "http://fvcproductions.com"
  bitbucket        :
  codepen          : "fvcproductions"
  dribbble         : "fvcproductions"
  flickr           :
  facebook         :
  foursquare       :
  github           : "fvcproductions"
  google_plus      : "fvcproductions2013"
  keybase          :
  instagram        :
  lastfm           :
  linkedin         : "fvcproductions"
  pinterest        :
  soundcloud       : "fvcproductions"
  spotify          : "fvcproductions"
  stackoverflow    : "3000467/fvcproductions" # "123456/username" (the last part of your profile url, e.g. http://stackoverflow.com/users/123456/username)
  steam            : "fvcproductions"
  tumblr           : "fvcproductions2013"
  twitter          : "fvcproductions"
  vine             :
  weibo            :
  xing             :
  youtube          : "fvcproductions2013" # "https://youtube.com/c/MichaelRoseDesign"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: ""
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /blog/:year/:month/:day/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /blog/page:num/
timezone: America/New_York # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - algoliasearch-jekyll

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Algolia
algolia:
  application_id   : 'LE508NV48J'
  index_name       : 'jekyll'
  read_only_api_key: 'd62499d6f6ac2e7850db91168db94083'
  excluded_files   :
    - 404.html
    - index.html

# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: all

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
  # _adventures
  - scope:
      path: ""
      type: adventures
    values:
      layout: single
      read_time: false
      comments: true
      share: true
      related: true
  # _feedback
  - scope:
      path: ""
      type: feedback
    values:
      layout: single
      read_time: false
      comments: true
      share: true
      related: true
  # _services
  - scope:
      path: ""
      type: services
    values:
      layout: single
      read_time: false
      comments: false
      share: true
      related: true
    # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      read_time: false
      comments: true
      share: true
      related: true
  # _speaking
  - scope:
      path: ""
      type: speaking
    values:
      layout: single
      read_time: false
      comments: true
      share: true
      related: true
  # _conferences
  - scope:
      path: ""
      type: conferences
    values:
      layout: single
      read_time: false
      comments: true
      share: true
      related: true
    # _hackathons
  - scope:
      path: ""
      type: hackathons
    values:
      layout: single
      read_time: false
      comments: true
      share: true
      related: true
  # _experience
  - scope:
      path: ""
      type: experience
    values:
      layout: single
      read_time: false
      comments: true
      share: true
      related: true
  # _education
  - scope:
      path: ""
      type: education
    values:
      layout: single
      read_time: false
      comments: true
      share: true
      related: true
    # _programs
  - scope:
      path: ""
      type: programs
    values:
      layout: single
      read_time: false
      comments: true
      share: true
      related: true
  # _volunteering
  - scope:
      path: ""
      type: volunteering
    values:
      layout: single
      read_time: false
      comments: true
      share: true
      related: true

# collections
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  services:
    output: true
    permalink: /services/:path/
  speaking:
    output: true
    permalink: /services/speaking/:path/
  feedback:
    output: true
    permalink: /feedback/:title/
  adventures:
    output: true
    permalink: /adventures/:path/
  conferences:
    output: true
    permalink: /conferences/:path/
  hackathons:
    output: true
    permalink: /hackathons/:path/
  programs:
    output: true
    permalink: /programs/:path/
  volunteering:
    output: true
    permalink: /volunteering/:path/
  experience:
    output: true
    permalink: /experience/:path/
  education:
    output: true
    permalink: /education/:path/