[build]
  publish = "dist"
  command = "gulp build"

[build.environment]
  TZ = "America/Los_Angeles"

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

# Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "https://fvcproductions.netlify.com/*"
  to = "/:splat"
  status = 301

[[redirects]]
  from = "https://podcast.fvcproductions.com/*"
  to = "/podcast/:splat"
  status = 301