---
pages:
- adventures/my-new-website-design.md
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: 
  config:
    required: true
  description: A short and sweet eye catcher.
- name: date
  label: Date
  type: text
  hidden: false
  default: ''
  description: When this post was finalized.
- name: description
  label: Description
  type: text
  hidden: false
  default: ''
  config:
    required: true
  description: A brief description of the post.
- name: banner
  label: Banner
  type: text
  hidden: false
  default: ''
  description: A link to the featured image that is hosted on Imgur.
- name: caption
  label: Caption
  type: text
  hidden: false
  default: ''
  description: Caption for banner image.
- name: bannerLink
  label: Bannerlink
  type: text
  hidden: false
  default: ''
  description: Link the featured image points to.
- name: link
  label: Link
  type: text
  hidden: false
  default: ''
  description: Link this post redirects to (assumes there will be no content).
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
- name: noComments
  label: Nocomments
  type: boolean
  hidden: false
  default: false
- name: categories
  label: Categories
  type: tag_list
  hidden: false
  default:
  - award
  - blog
  - conference
  - education
  - experience
  - hackathon
  - program
  - speaking
  - volunteering
  - portfolio
  - certainties
  - coding
  - creativity
  - book
  - design
  - mobile
  - oss
  - presentation
  - research
  - tutorial
  - video
  - web
  - 2017
  - 2016
  - 2015
  - bootcamps
  - hourofcode
  - wizard
  - typescript101
  - webdesign
  description: Categories help differentiate what kind of post this is.
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default:
  - insert tags for article
  description: Tags are useful for SEO.
- type: datetime
  name: ''
  label: ''
