---
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: 
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- name: description
  label: Description
  type: text
  hidden: false
  default: A brief description goes here.
- name: banner
  label: Banner
  type: text
  hidden: false
  default: Link to image on Imgur.
- name: caption
  label: Caption
  type: text
  hidden: false
  default: Caption for banner image.
- name: bannerLink
  label: Bannerlink
  type: text
  hidden: false
  default: Link image points to.
- name: link
  label: Link
  type: text
  hidden: false
  default: Link article redirects to.
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
- name: alphabetical
  label: Alphabetical
  type: boolean
  hidden: false
  default: true
- name: noComments
  label: Nocomments
  type: boolean
  hidden: false
  default: true
- name: adventures
  label: Adventures
  type: boolean
  hidden: false
  default: true
- name: archive
  label: Archive
  type: boolean
  hidden: false
  default: true
- name: awards
  label: Awards
  type: boolean
  hidden: false
  default: true
- name: blog
  label: Blog
  type: boolean
  hidden: false
  default: true
- name: contact
  label: Contact
  type: boolean
  hidden: false
  default: true
- name: portfolio
  label: Portfolio
  type: boolean
  hidden: false
  default: true
- name: speaking
  label: Speaking
  type: boolean
  hidden: false
  default: true
- name: isotope
  label: Isotope
  type: boolean
  hidden: false
  default: true
- name: categories
  label: Categories
  type: tag_list
  hidden: false
  default:
  - award
  - blog
  - conference
  - education
  - experience
  - hackathon
  - program
  - speaking
  - volunteering
  - portfolio
  - certainties
  - coding
  - creativity
  - book
  - design
  - mobile
  - oss
  - presentation
  - research
  - tutorial
  - video
  - web
  - 2017
  - 2016
  - 2015
  - bootcamps
  - hourofcode
  - wizard
  - typescript101
  - webdesign
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default:
  - insert tags for article
