---
label: default
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
  config:
    required: true
  description: A short and sweet eye catcher.
- type: datetime
  name: date
  label: Date Published
  description: When this post was finalized.
- name: description
  label: Description
  type: text
  hidden: false
  default: ''
  config:
    required: true
  description: A brief description of this post.
- type: text
  name: image
  label: Featured Image
  config:
    required: false
  description: Link to hero image that is hosted on Imgur.
- name: link
  label: Redirect Link
  type: text
  hidden: false
  default: ''
  description: Link this post redirects to.
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
  description: Keep as draft until fully finalized.
- name: noComments
  label: No Comments
  type: boolean
  hidden: true
  default: false
  description: Comments are enabled by default.
- type: list
  config:
    min: '1'
    use_select: true
    source:
      type: simple
    options:
    - blog
    - portfolio
    - volunteering
    - conference
    - award
    - speaking
    - program
    - review
    - hackathon
    - education
    - press
    - experience
    - talk
    - freelancing
    - mentoring
    - experience
  label: Categories
  name: categories
  default: []
  description: Categories help differentiate what kind of post this is.
- type: tag_list
  description: Tags help with the SEO of the post.
  name: tags
  label: Tags
pages:
- site/content/adventures/2018-08-15-code-2040.md.md
- site/content/adventures/2015-08-28-fullstack-academy---blog-post-banners.md
- site/content/adventures/2014-11-16-needs-flavours.md
- site/content/adventures/2014-11-11-new-wordpress-theme---tdeditor.md
- site/content/adventures/2014-10-15-custom-website-flavicons.md
- site/content/adventures/2016-01-01-el-capitan----strict--yosemite----strict.md
