---
new_page_extension: md
auto_deploy: true
admin_path: site/.forestry
webhook_url: 
sections:
- path: site/content
  label: Pages
  create: all
- path: site/content/adventures
  label: Adventures
  create: all
upload_dir: site/static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
version: 0.31.1
