baseURL = "https://fvcproductions.com"
defaultContentLanguage = "en"
disqusShortname = "fvcproductions"
enableEmoji = true
footnoteReturnLinkContents = "↩"
googleAnalytics = "UA-63190978-3"
languageCode = "en-us"
metaDataFormat = "yaml"
preserveTaxonomyNames = false
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "manni"
title = "FVCproductions"
[author]
copyright = "©️ FVCproductions"
name = "Frances Coronel"
[[menu.main]]
name = "Home 🏠"
url = "/"
weight = 1
[outputFormats.RSS]
baseName = "feed"
mediatype = "application/rss"
[outputs]
home = ["HTML", "AMP", "RSS"]
page = ["HTML", "AMP"]
[params]
copyright = "FVCproductions"
description = "I like to dabble with things that ought to be dabbled with. 🍫️🍓️️"
headline = "Hey there, I'm Frances! 👋\u{1F3FD}️"
year = 2013
[permalinks]
adventures = "/:year/:month/:day/:title/"
blog = "/blog/:year/:month/:day/:title/"
portfolio = "/portfolio/:year/:month/:day/:title/"
[social]
amazon = "AGCK4BOZOTAMEA4HTNM2DF7AL4RA"
angellist = "fvcproductions"
behance = "fvcproductions"
calendly = "fvcproductions"
codepen = "fvcproductions"
deviantart = "fvcproductions"
dribbble = "fvcproductions"
email = "hello@fvcproductions.com"
etsy = "fvcproductions"
freecodecamp = "fvcproductions"
github = "fvcproductions"
gitlab = "fvcproductions"
goodreads = "fvcproductions"
googleplus = "fvcproductions2013"
hackernews = "fvcproductions"
houzz = "fvcproductions"
imgur = "fvcproductions"
linkedin = "fvcproductions"
medium = "@fvcproductions"
meetup = "182920007"
paypal = "fvcproductions"
producthunt = "fvcproductions"
quora = "fvcproductions"
reddit = "fvcproductions"
rottentomatoes = "966430171"
scribd = "194063411/FVCproductions"
slideshare = "fvcproductions"
soundcloud = "fvcproductions"
spotify = "fvcproductions"
stackexchange = "3595658/fvcproductions"
stackoverflow = "3000467/fvcproductions"
steam = "fvcproductions"
trello = "fvcproductions"
tumblr = "fvcproductions2013"
twitter = "fvcproductions"
vimeo = "fvcproductions"
wordpress = "fvcproductions"
yelp = "E6StflkoWAutmRZ31zNTug"
youtube = "fvcproductions2013"
