backend:
  name: git-gateway
  branch: production
  publish_mode: editorial_workflow
  media_folder: "static/images" # Media files will be stored in the repo under static/images/uploads
  public_folder: "dist/images" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "adventures" # Used in routes, e.g., /admin/collections/blog
    label: "Adventures" # Used in the UI
    folder: "adventures" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Banner", name: "banner", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Embedly", name: "embedly", widget: "boolean"}

  - name: bannerLink
    label: Bannerlink
    type: text
    hidden: false
    default: Link image points to.
  - name: link
    label: Link
    type: text
    hidden: false
    default: Link article redirects to.
  - name: categories
    label: Categories
    type: tag_list
    hidden: false
    default:
    - blog
    - conference
    - education
    - experience
    - hackathon
    - program
    - speaking
    - volunteering
  - name: tags
    label: Tags
    type: tag_list
    hidden: false
    default:
    - insert tags for article
